dist: xenial

language: php

php:
  - "7.3"
  - "5.6"

install:
  - npm install

script:
  - npm run lint

branches:
  only:
  - master
  - develop

notifications:
  email: false

cache:
  npm: true
  directories:
    - $HOME/.composer/cache
